name: env_scanpy
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - star=2.7.9  # Version spécifiée par l'utilisateur
  - cufflinks=2.2.1
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - seaborn
  - statsmodels
  - scanpy
  - anndata
  - tensorflow
  - pytorch
  - torchvision
  - plotly
  - bokeh
  - altair
  - plotnine
  - holoviews
  - hvplot.pandas
  - palmerpenguins 
  - palettable
  - pip
  - pip:
    - jupyterlab
    - pydeseq2 