name: env2
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - ipykernel
  - numpy
  - pandas
  - biopython
  - scanpy
  - anndata
  - pysam
  - samtools
  - bedtools
  - bowtie2
  - pip
  - pip:
    - deeptools
    - gseapy 